dist: bionic

language: generic #python
#python:
#- '3.8'

cache:
  pip: true
  directories:
  - "$HOME/db/"
env:
  global:
  #- GIT_NAME: spirillen
  - GIT_NAME: Travis CI
  #- GIT_EMAIL: "travis@travis-ci.org"
  - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
  - TRAVIS_REPO_SLUG: "${TRAVIS_REPO_SLUG}"
  - GIT_BRANCH: $"{TRAVIS_BRANCH}"
  - TZ: UTC
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/dev-tools/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: yes
  - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
  - PYFUNCEBLE_DB_HOST="${DB_HOST}"
  - PYFUNCEBLE_DB_NAME="${DB_NAME}"
  - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
  - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
  - PYFUNCEBLE_DB_PORT="${DB_PORT}"
  #- DEBUG_PYFUNCEBLE: true
  #- DEBUG_PYFUNCEBLE_ON_SCREEN: true
  - PYTHON_VERSION: 3.8.5
  #- secure: s2pGoOKhtxbI0TBrhuM1tGPk6c14GITgBPrL41cn8nRDljYp7H8VDngS8pnXV1A+bLN0Y2rnCJ8yp6MljkclChocvqvS05N+uxT2HfHg142Yvm1xKs+GM2mjuAAZRjNFNM7y2MyM+LMTqF1cN5w2p5sKMpcaS6rYKz8fnKu+e15llMnWKCfKYyJ8DUuvXS5Rsc6ZtesCtN/4ol44hrWIlA9ogeejaj4/foYAmK1YWUg48Wy+5mjso644mBJNdWSNSBMrX/DaLJogFroqrrnYZ++1Rjyn0oq3IuqEU61vZ33bztLr6kMW2kDITSxMLV1VGmZw57FDZyXnCzK2iz1xaQLf6ccHx8rHSxxS7o0GGUCAOw7Ydrdy2x+KmYtr7PRyL2CfjgFZMdN/4MtWuJofXymyMl+aC+7s9diTfpErKDUInI2RbvFzBaHxQl3jS0S4bGQnDFCjsF04ZkBrs6BBDAtWu+vvIREhNAufrmL5nh/NcECbpHy2qXCoauZW1NE9/SuvH0ZSOT1HoQyylYKbjqLHNC4UPedMX14mq5mJPC/XHsJgGqYyiV6X57d88esEpCzey1yV68PwRJtPqDb1XNTiFkaqmpIPhpBzwmeRuuT0wZQWC+87j8c2A/xTPM2ScRhhb8GRXIDR0QpuquVXvfD66GV9Y4uRn5k20S4okEI=
addons:
  mariadb: '10.4'
  apt:
    packages:
    - dos2unix
    - msttcorefonts
    - lsof

install:
  - sudo bash "${TRAVIS_BUILD_DIR}/dev-tools/setup_recursor.sh"
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  #- pip -q install --no-cache-dir -U pyfunceble-dev ultimate-hosts-blacklist-whitelist dnspython[dnssec,idna]
  - pip -q install --no-cache-dir -U git+https://github.com/funilrys/PyFunceble@dev ultimate-hosts-blacklist-whitelist-dev dnspython[dnssec,idna]
  - pyfunceble --version

git:
  depth: 2
branches:
  only:
  - master
  #- pyfunceble-processing

matrix:
  fast_finish: true

script:
  - sudo systemctl restart mariadb.service
  - sudo mariadb -u root -h localhost -e "CREATE DATABASE PyFunceble DEFAULT CHARACTER
    SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - sudo mariadb -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  - sudo mariadb -u root -h localhost -e "CREATE USER 'PyFunceble'@'localhost' IDENTIFIED
    BY 'PyFunceble';"
  - sudo mariadb -u root -h localhost -e "GRANT ALL PRIVILEGES ON *.* TO 'PyFunceble'@'localhost';"
  - if [ -f ${HOME}/db/pyfunceble.sql ]; then sudo mariadb --user=PyFunceble --password=PyFunceble
    PyFunceble < ${HOME}/db/pyfunceble.sql; fi
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash dev-tools/PrepareData.sh && bash dev-tools/DataTesting.sh && sudo mkdir -p
    ${HOME}/db/ && sudo mariadb-dump --user=PyFunceble --password=PyFunceble --opt PyFunceble
    > ${HOME}/db/pyfunceble.sql; fi'
  - - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
